[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  { id = "check-merge-conflict" },
  { id = "check-yaml" },
  { id = "check-toml" },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "cargo-fmt"
name = "cargo fmt --check"
language = "system"
entry = "cargo fmt --all -- --check"
pass_filenames = false
types = ["rust"]

[[repos.hooks]]
id = "cargo-clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy --workspace --all-targets -- -D warnings"
pass_filenames = false
types = ["rust"]
